apiVersion: v2
name: contact-app
description: Two-tier contact form (Flask) + PostgreSQL for RKE2 and AWS EKS
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Intern Assignment
