{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contact-app.serviceAccountName" . }}
  labels: {{- include "contact-app.labels" . | nindent 4 }}
# App does not talk to the Kubernetes API, so never mount a token.
automountServiceAccountToken: false
{{- end }}
